

```{r}
library(forecast)
library(graphics)
library(TTR)
library(TSA)
library(readxl)
library(ggplot2)
```

```{r}
temp <- read_excel("D:/KULIAH/SEM 5/MPDW/laporan_iklim_harian-250831182901.xlsx")
temp
```

```{r}
subset_data <- temp[125:250, ]

data1 <- data.frame(
  Periode = 125:250,
  TAVG = subset_data$TAVG)
```


```{r}
head(data1)

```


```{r}
View(data1)
str(data1)
```

```{r}
dim(data1)
```
```{r}
data1.ts <- ts(data1$TAVG)
```

```{r}
summary(data1.ts)
```

```{r}
ts.plot(data1.ts, xlab="Time Period ", ylab="Reading", 
        main = "Time Series Plot")
points(data1.ts)
```

```{r}
n <- nrow(data1)

n_train <- floor(0.8 * n)

training_ma <- data1[1:n_train, ]
testing_ma  <- data1[(n_train+1):n, ]

train_ma.ts <- ts(training_ma$TAVG)
test_ma.ts  <- ts(testing_ma$TAVG)
```

```{r}
plot(data1.ts, col="red",main="Plot semua data")
points(data1.ts)
```

```{r}
plot(train_ma.ts, col="blue",main="Plot data latih")
points(train_ma.ts)
```

```{r}
plot(test_ma.ts, col="blue",main="Plot data uji")
points(test_ma.ts)
```

```{r}
# Pastikan Periode numeric
training_ma$Periode <- as.numeric(training_ma$Periode)
testing_ma$Periode  <- as.numeric(testing_ma$Periode)

# Pastikan TAVG numeric
training_ma$TAVG <- as.numeric(training_ma$TAVG)
testing_ma$TAVG  <- as.numeric(testing_ma$TAVG)

# Gabungkan supaya gampang kasih legend
training_ma$Jenis <- "Data Latih"
testing_ma$Jenis  <- "Data Uji"
plot_data <- rbind(training_ma, testing_ma)

# Plot dengan legend otomatis
library(ggplot2)

ggplot(plot_data, aes(x = Periode, y = TAVG, color = Jenis)) +
  geom_line() +
  labs(x = "Periode Waktu", y = "TAVG", color = "Keterangan") +
  scale_color_manual(values = c("Data Latih" = "blue", "Data Uji" = "red")) +
  theme_bw() +
  theme(legend.position = "bottom",
        plot.caption = element_text(hjust = 0.5, size = 12))

```

```{r}
data.sma<-SMA(train_ma.ts, n=4)
data.sma
```

```{r}
data.ramal<-c(NA,data.sma)
data.ramal 
```

```{r}
data.gab<-cbind(
  aktual=c(data1.ts),
  pemulusan=c(data.sma,rep(NA,24)),
  ramalan=c(data.ramal,rep(data.ramal[length(data.ramal)],23)))

data.gab
```

```{r}
ts.plot(data1.ts, xlab="Time Period ", ylab="TAVG", main= "SMA N=4 Data TAVG")
points(data1.ts)
lines(data.gab[,2],col="green",lwd=2)
lines(data.gab[,3],col="red",lwd=2)
legend("topleft",c("data aktual","data pemulusan","data peramalan"), lty=8, col=c("black","green","red"), cex=0.5)
```

```{r}

train_ma.ts <- as.numeric(train_ma.ts)

data.ramal <- as.numeric(data.ramal)

n <- length(train_ma.ts)
error_train.sma <- train_ma.ts - data.ramal[1:n]

SSE_train.sma  <- sum(error_train.sma[5:n]^2, na.rm = TRUE)
MSE_train.sma  <- mean(error_train.sma[5:n]^2, na.rm = TRUE)
MAPE_train.sma <- mean(abs(error_train.sma[5:n] / train_ma.ts[5:n]) * 100,
                       na.rm = TRUE)

akurasi_train.sma <- matrix(c(SSE_train.sma, MSE_train.sma, MAPE_train.sma),
                            nrow = 3, byrow = TRUE,
                            dimnames = list(c("SSE", "MSE", "MAPE"),
                                            c("Akurasi m = 4")))
akurasi_train.sma


```

```{r}
# Pastikan numeric
test_ma.ts <- as.numeric(test_ma.ts)
data_pred  <- as.numeric(data.gab[97:120, 3])   # kolom ke-3 jadi numeric vector

# Samakan panjang (seharusnya sama 24 data kalau 97:120)
n <- length(test_ma.ts)

# Hitung error
error_test.sma <- test_ma.ts - data_pred[1:n]

# SSE, MSE, MAPE
SSE_test.sma  <- sum(error_test.sma^2, na.rm = TRUE)
MSE_test.sma  <- mean(error_test.sma^2, na.rm = TRUE)
MAPE_test.sma <- mean(abs(error_test.sma / test_ma.ts) * 100, na.rm = TRUE)

# Buat matriks hasil
akurasi_test.sma <- matrix(c(SSE_test.sma, MSE_test.sma, MAPE_test.sma),
                           nrow = 3, byrow = TRUE,
                           dimnames = list(c("SSE", "MSE", "MAPE"),
                                           c("Akurasi m = 4")))

akurasi_test.sma

```

```{r}
dma <- SMA(data.sma, n = 4)
At <- 2*data.sma - dma
Bt <- 2/(4-1)*(data.sma - dma)
data.dma<- At+Bt
data.ramal2<- c(NA, data.dma)

t = 1:24
f = c()

for (i in t) {
  f[i] = At[length(At)] + Bt[length(Bt)]*(i)
}

data.gab2 <- cbind(aktual = c(data1.ts), 
                   pemulusan1 = c(data.sma,rep(NA,24)),
                   pemulusan2 = c(dma, rep(NA,24)),
                   At = c(At, rep(NA,24)), 
                   Bt = c(Bt,rep(NA,24)),
                   ramalan = c(data.ramal2, f[-1]))
data.gab2
```

```{r}
ts.plot(data1.ts, xlab="Time Period ", ylab="TAVG", main= "DMA N=4 Data TAVG")
points(data1.ts)
lines(data.gab2[,3],col="green",lwd=2)
lines(data.gab2[,6],col="red",lwd=2)
legend("topleft",c("data aktual","data pemulusan","data peramalan"), lty=8, col=c("black","green","red"), cex=0.8)
```

```{r}
train_ma.ts <- as.numeric(train_ma.ts)

data.ramal <- as.numeric(data.ramal)

error_train.dma = train_ma.ts-data.ramal2[1:length(train_ma.ts)]

SSE_train.dma = sum(error_train.dma[8:length(train_ma.ts)]^2)
MSE_train.dma = mean(error_train.dma[8:length(train_ma.ts)]^2)
MAPE_train.dma = mean(abs((error_train.dma[8:length(train_ma.ts)]/train_ma.ts[8:length(train_ma.ts)])*100))

akurasi_train.dma <- matrix(c(SSE_train.dma, MSE_train.dma, MAPE_train.dma))
row.names(akurasi_train.dma)<- c("SSE", "MSE", "MAPE")
colnames(akurasi_train.dma) <- c("Akurasi m = 4")
akurasi_train.dma
```

```{r}
# Pastikan numeric
test_ma.ts <- as.numeric(test_ma.ts)
data_pred2 <- as.numeric(data.gab2[97:120, 6])   # ambil kolom ke-6 sebagai numeric vector

# Samakan panjang (seharusnya sama dengan panjang test_ma.ts)
n <- length(test_ma.ts)

# Hitung error
error_test.dma <- test_ma.ts - data_pred2[1:n]

# Hitung metrik akurasi
SSE_test.dma  <- sum(error_test.dma^2, na.rm = TRUE)
MSE_test.dma  <- mean(error_test.dma^2, na.rm = TRUE)
MAPE_test.dma <- mean(abs(error_test.dma / test_ma.ts) * 100, na.rm = TRUE)

# Simpan hasil ke matriks
akurasi_test.dma <- matrix(c(SSE_test.dma, MSE_test.dma, MAPE_test.dma),
                           nrow = 3, byrow = TRUE,
                           dimnames = list(c("SSE", "MSE", "MAPE"),
                                           c("Akurasi m = 4")))

akurasi_test.dma

```

```{r}
# jumlah baris data
n <- nrow(data1)

# hitung batas 80%
n_train <- floor(0.8 * n)

# bagi data
training <- data1[1:n_train, ]
testing  <- data1[(n_train+1):n, ]

# ubah ke time series
train.ts <- ts(training$TAVG)
test.ts  <- ts(testing$TAVG)
```

```{r}
library(forecast)

# Pastikan data numeric dan tanpa NA
train.ts <- ts(as.numeric(train.ts))
train.ts <- na.omit(train.ts)

# SES dengan alpha otomatis
ses.1 <- ses(train.ts, h = 10)

# Plot hasil
plot(ses.1)

```

```{r}
ses.2 <- ses(train.ts, h = 10, alpha = 0.2)
plot(ses.2)
```

```{r}
ses.3<- ses(train.ts, h = 10, alpha = 0.7)
plot(ses.3)
```

```{r}
autoplot(ses.1) +
  autolayer(fitted(ses.1), series="Fitted") +
  ylab("Membaca") + xlab("Periode")
```

```{r}
ses1<- HoltWinters(train.ts, gamma = FALSE, beta = FALSE, alpha = 0.2)
plot(ses1)
```

```{r}
ramalan1<- forecast(ses1, h=10)
ramalan1
```

```{r}
ses2<- HoltWinters(train.ts, gamma = FALSE, beta = FALSE, alpha = 0.7)
plot(ses2)
```

```{r}
ramalan2<- forecast(ses2, h=10)
ramalan2
```

```{r}
ses.opt <- ses(train.ts, h = 10, alpha = NULL)
plot(ses.opt)
```

```{r}
HWopt<- HoltWinters(train.ts, gamma = FALSE, beta = FALSE,alpha = NULL)
HWopt
```

```{r}
plot(HWopt)
```

```{r}
ramalanopt<- forecast(HWopt, h=10)
ramalanopt
```

```{r}
SSE1<-ses1$SSE
MSE1<-ses1$SSE/length(train.ts)
RMSE1<-sqrt(MSE1)

akurasi1 <- matrix(c(SSE1,MSE1,RMSE1))
row.names(akurasi1)<- c("SSE", "MSE", "RMSE")
colnames(akurasi1) <- c("Akurasi lamda=0.2")
akurasi1
```

```{r}
SSE2<-ses2$SSE
MSE2<-ses2$SSE/length(train.ts)
RMSE2<-sqrt(MSE2)

akurasi2 <- matrix(c(SSE2,MSE2,RMSE2))
row.names(akurasi2)<- c("SSE", "MSE", "RMSE")
colnames(akurasi2) <- c("Akurasi lamda=0.7")
akurasi2
```

```{r}
fitted1<-ramalan1$fitted
sisaan1<-ramalan1$residuals
head(sisaan1)
```

```{r}
# Pastikan numeric
training$TAVG <- as.numeric(training$TAVG)
fitted_val <- as.numeric(ramalan1$fitted)

# Hitung residual
resid1 <- training$TAVG - fitted_val
head(resid1)

```

```{r}
SSE.1=sum(sisaan1[2:length(train.ts)]^2)
SSE.1
```

```{r}
MSE.1 = SSE.1/length(train.ts)
MSE.1
```

```{r}
MAPE.1 = sum(abs(sisaan1[2:length(train.ts)]/train.ts[2:length(train.ts)])*
               100)/length(train.ts)
MAPE.1
```

```{r}
akurasi.1 <- matrix(c(SSE.1,MSE.1,MAPE.1))
row.names(akurasi.1)<- c("SSE", "MSE", "MAPE")
colnames(akurasi.1) <- c("Akurasi lamda=0.2")
akurasi.1
```

```{r}
fitted2<-ramalan2$fitted
sisaan2<-ramalan2$residuals
head(sisaan2)
```

```{r}
# Pastikan numeric
training$TAVG <- as.numeric(training$TAVG)
fitted_val2 <- as.numeric(ramalan2$fitted)

# Hitung residual
resid2 <- training$TAVG - fitted_val2
head(resid2)
```

```{r}
SSE.2=sum(sisaan2[2:length(train.ts)]^2)
SSE.2
```

```{r}
MSE.2 = SSE.2/length(train.ts)
MSE.2
```

```{r}
MAPE.2 = sum(abs(sisaan2[2:length(train.ts)]/train.ts[2:length(train.ts)])*
               100)/length(train.ts)
MAPE.2
```

```{r}
akurasi.2 <- matrix(c(SSE.2,MSE.2,MAPE.2))
row.names(akurasi.2)<- c("SSE", "MSE", "MAPE")
colnames(akurasi.2) <- c("Akurasi lamda=0.7")
akurasi.2
```

```{r}
# jumlah observasi uji
n_test <- nrow(testing)

# error (ramalan - aktual), samakan panjang dan tipe numeric
e1   <- as.numeric(ramalan1$mean)[1:n_test] - as.numeric(testing$TAVG)
e2   <- as.numeric(ramalan2$mean)[1:n_test] - as.numeric(testing$TAVG)
eopt <- as.numeric(ramalanopt$mean)[1:n_test] - as.numeric(testing$TAVG)

# SSE / MSE / RMSE untuk masing-masing model (abaikan NA)
SSEtesting1  <- sum(e1^2,  na.rm = TRUE)
MSEtesting1  <- mean(e1^2, na.rm = TRUE)
RMSEtesting1 <- sqrt(MSEtesting1)

SSEtesting2  <- sum(e2^2,  na.rm = TRUE)
MSEtesting2  <- mean(e2^2, na.rm = TRUE)
RMSEtesting2 <- sqrt(MSEtesting2)

SSEtestingopt  <- sum(eopt^2,  na.rm = TRUE)
MSEtestingopt  <- mean(eopt^2, na.rm = TRUE)
RMSEtestingopt <- sqrt(MSEtestingopt)

# Tabel ringkas
akurasitesting_SSE <- matrix(c(SSEtesting1, SSEtesting2, SSEtestingopt),
                             nrow = 3,
                             dimnames = list(c("SSE1","SSE2","SSEopt"), "Nilai"))
akurasitesting_MSE <- matrix(c(MSEtesting1, MSEtesting2, MSEtestingopt),
                             nrow = 3,
                             dimnames = list(c("MSE1","MSE2","MSEopt"), "Nilai"))
akurasitesting_RMSE <- matrix(c(RMSEtesting1, RMSEtesting2, RMSEtestingopt),
                              nrow = 3,
                              dimnames = list(c("RMSE1","RMSE2","RMSEopt"), "Nilai"))

akurasitesting_SSE
```

```{r}
akurasitesting_MSE
```

```{r}
akurasitesting_RMSE
```

```{r}
train.ts <- ts(as.numeric(training$TAVG), frequency = 12)  # contoh freq bulanan

# pastikan test data numeric
test.ts <- as.numeric(testing$TAVG)

# fit SES dengan horizon sesuai panjang data uji
ramalan1 <- ses(train.ts, h = length(test.ts))

# hitung akurasi terhadap data uji
accuracy(ramalan1, test.ts)

```

```{r}
des.1<- HoltWinters(train.ts, gamma = FALSE, beta = 0.2, alpha = 0.2)
plot(des.1)
```

```{r}
ramalandes1<- forecast(des.1, h=10)
ramalandes1
```

```{r}
des.2<- HoltWinters(train.ts, gamma = FALSE, beta = 0.3, alpha = 0.6)
plot(des.2)
```

```{r}
ramalandes2<- forecast(des.2, h=10)
ramalandes2

```

```{r}
plot(data1.ts)
lines(des.1$fitted[,1], lty=2, col="blue")
lines(ramalandes1$mean, col="red")
```

```{r}
des.opt<- HoltWinters(train.ts, gamma = FALSE)
des.opt
```

```{r}
plot(des.opt)
```

```{r}
ramalandesopt<- forecast(des.opt, h=10)
ramalandesopt
```

```{r}
ssedes.train1<-des.1$SSE
msedes.train1<-ssedes.train1/length(train.ts)
sisaandes1<-ramalandes1$residuals
head(sisaandes1)
```

```{r}
mapedes.train1 <- sum(abs(sisaandes1[3:length(train.ts)]/train.ts[3:length(train.ts)])
                      *100)/length(train.ts)

akurasides.1 <- matrix(c(ssedes.train1,msedes.train1,mapedes.train1))
row.names(akurasides.1)<- c("SSE", "MSE", "MAPE")
colnames(akurasides.1) <- c("Akurasi lamda=0.2 dan gamma=0.2")
akurasides.1
```

```{r}
ssedes.train2<-des.2$SSE
msedes.train2<-ssedes.train2/length(train.ts)
sisaandes2<-ramalandes2$residuals
head(sisaandes2)
```

```{r}
mapedes.train2 <- sum(abs(sisaandes2[3:length(train.ts)]/train.ts[3:length(train.ts)])
                      *100)/length(train.ts)

akurasides.2 <- matrix(c(ssedes.train2,msedes.train2,mapedes.train2))
row.names(akurasides.2)<- c("SSE", "MSE", "MAPE")
colnames(akurasides.2) <- c("Akurasi lamda=0.6 dan gamma=0.3")
akurasides.2
```

```{r}
# pastikan test data numeric
testing$TAVG <- as.numeric(testing$TAVG)

# pastikan forecast jadi numeric
prediksi_des1 <- as.numeric(ramalandes1$mean)

# samakan panjang
n <- length(testing$TAVG)
selisihdes1 <- prediksi_des1[1:n] - testing$TAVG[1:n]

selisihdes1

```

```{r}
SSEtestingdes1<-sum(selisihdes1^2)
MSEtestingdes1<-SSEtestingdes1/length(testing$TAVG)
MAPEtestingdes1<-sum(abs(selisihdes1/testing$TAVG)*100)/length(testing$TAVG)
```


```{r}
# pastikan test data numeric
testing$TAVG <- as.numeric(testing$TAVG)

# pastikan hasil ramalan numeric
prediksi_des2 <- as.numeric(ramalandes2$mean)

# ambil sesuai panjang data uji
n <- length(testing$TAVG)
selisihdes2 <- prediksi_des2[1:n] - testing$TAVG[1:n]

selisihdes2

```

```{r}
SSEtestingdes2<-sum(selisihdes2^2)
MSEtestingdes2<-SSEtestingdes2/length(testing$TAVG)
MAPEtestingdes2<-sum(abs(selisihdes2/testing$TAVG)*100)/length(testing$TAVG)
```


```{r}
# Pastikan data uji numeric
testing$TAVG <- as.numeric(testing$TAVG)

# Pastikan hasil ramalan numeric
prediksi_desopt <- as.numeric(ramalandesopt$mean)

# Samakan panjang
n <- length(testing$TAVG)
selisihdesopt <- prediksi_desopt[1:n] - testing$TAVG[1:n]

selisihdesopt

```

```{r}
# Hitung akurasi DES Opt
SSEtestingdesopt  <- sum(selisihdesopt^2, na.rm=TRUE)
MSEtestingdesopt  <- mean(selisihdesopt^2, na.rm=TRUE)
MAPEtestingdesopt <- mean(abs(selisihdesopt / testing$TAVG) * 100, na.rm=TRUE)

# Gabungkan semua hasil ke dalam matriks
akurasitestingdes <- matrix(
  c(SSEtestingdes1, MSEtestingdes1, MAPEtestingdes1,
    SSEtestingdes2, MSEtestingdes2, MAPEtestingdes2,
    SSEtestingdesopt, MSEtestingdesopt, MAPEtestingdesopt),
  nrow = 3, byrow = TRUE
)

row.names(akurasitestingdes) <- c("SSE", "MSE", "MAPE")
colnames(akurasitestingdes)  <- c("DES Ske1", "DES Ske2", "DES Opt")

akurasitestingdes

```


Berdasarkan hasil perhitungan pada HTML, metode terbaik adalah Holt-Winters karena memberikan nilai error (MAPE, MSE, SSE, RMSE) paling kecil dibandingkan metode lain, sehingga akurasinya paling tinggi.
